version: '3.7'
services:
  rails-dev:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    profiles:
      - dev
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./env/.env
    profiles:
      - prod
  rails-prod:
    build: ./
    ports:
      - '80:3000'
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    env_file:
      - ./env/.env
    depends_on:
      - db  # add all dependant container
    profiles:
      - prod

volumes:
  postgres: # named volume
